# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
#image: gcc

stages:
  - build
  - test
#  - package

include:
# Debian
#.  - local: .gitlab/ci/debian-with-deps.yml       # images with deps
#  - local: .gitlab/ci/debian.yml

# Fedora
#.  - local: .gitlab/ci/fedora.yml

# FreeBSD
#.  - local: .gitlab/ci/freebsd-1-stage.yml       # Docker@FreeBSD, fastest
#  - local: .gitlab/ci/freebsd-3-stage.yml       # Docker@FreeBSD, fastest

# AltLinux
#  - local: .gitlab/ci/altlinux.yml       # turned off
# Fast Yandex mirror broken from time to time
# Slow Vendor repository is slow and inconvenient so

# incomplete
# Gentoo build and test
#  - local: .gitlab/ci/gentoo-build-n-test.yml

# Gentoo test
  - local: .gitlab/ci/gentoo-test.yml

# incomplete
# ArchLinux
#  - local: .gitlab/ci/archlinux.yml
