#!/bin/sh

TARGET=restracer

# Default toolchain is GCC
#if [ "$CC" == "" ]; then CC=gcc; export CC; fi
#if [ "$CXX" == "" ]; then CXX=g++; export CXX; fi
#if [ "$LD" == "" ]; then LD=ld; fi

#if [ "$CC" == "" ]; then CC=clang; fi
#if [ "$CXX" == "" ]; then CXX=clang; fi
#if [ "$LD" == "" ]; then LD=clang; fi

#CC=$TARGET-$(CC) CXX=$TARGET-$(CXX) LD=$TARGET-$(LD) make $*
CC=$TARGET-cc CXX=$TARGET-c++ LD=$TARGET-ld make $*
